# Generated by Django 5.2 on 2025-05-06 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã đặt tour')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('adults', models.PositiveSmallIntegerField(default=1, verbose_name='Số người lớn')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Số trẻ em')),
                ('special_request', models.TextField(blank=True, verbose_name='Yêu cầu đặc biệt')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Chuyển khoản ngân hàng'), ('credit_card', 'Thẻ tín dụng'), ('momo', 'Ví MoMo'), ('zalopay', 'ZaloPay'), ('cash', 'Tiền mặt')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('paid', 'Đã thanh toán'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour', verbose_name='Tour')),
                ('tour_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tourdate', verbose_name='Ngày khởi hành')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Đặt tour',
                'verbose_name_plural': 'Đặt tour',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Chuyển khoản ngân hàng'), ('credit_card', 'Thẻ tín dụng'), ('momo', 'Ví MoMo'), ('zalopay', 'ZaloPay'), ('cash', 'Tiền mặt')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thanh toán')),
                ('status', models.BooleanField(default=False, verbose_name='Thành công')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='Đơn đặt tour')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-payment_date'],
            },
        ),
    ]
