# Generated by Django 5.2 on 2025-05-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Tiêu đề phụ')),
                ('image_url', models.CharField(max_length=255, verbose_name='Đường dẫn hình ảnh')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Đường dẫn liên kết')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên địa điểm')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug URL')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('image', models.CharField(max_length=255, verbose_name='Đường dẫn hình ảnh')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Phổ biến')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Điểm đến',
                'verbose_name_plural': 'Điểm đến',
                'ordering': ['name'],
            },
        ),
    ]
